spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2

            - id: posts-service
              uri: lb://POSTS-SERVICE
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

            - id: connection-service
              uri: lb://CONNECTION-SERVICE
              predicates:
                - Path=/api/v1/connections/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

server:
  port: 9024

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9023/eureka/


jwt.secretKey: asdfuasjf9a8s7fd89ihq34kljruyf98ayshcs kdhfioaf suyfdc jha890sduf
